devices:
  R1:
    device_type: cisco_ios
    host: 192.168.100.2
    password: gAAAAABnwlw9bzea2wK4ENrZHIs4fcWoXvqZYKhNj91bynbzIoE7hanZ_3xUcrmXDf-gGwgVZpp0K9k_WQKviy3howk-g0VlBA==
    port: 22
    secret: gAAAAABnwlw9jsw2fj_UjADgumqqqvQSzmELFYSdMuV6oIDxt-PC10zzlSyk5umBNHaYq9fzrAuyxuveiyj8yYpg9utFle3nCg==
    username: admin
syslog_server:
  ip: 192.168.100.10
